### ISSUE TITLE
Bugs:Archlinux下编译后无法运行。

### ISSUE THREAD

**Issue by zxp19821005** [horenjs/horen#4]
如题。
源采用的是最新的版本
编译完成后，运行`horen`提示：
```
$ ./horen 
(node:204704) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at initLogger (/home/zxp-endeavouros/.cache/paru/clone/horen-git/src/horen.git/out/horen-linux-x64/resources/app/dist/main.js:47228:32)
    at /home/zxp-endeavouros/.cache/paru/clone/horen-git/src/horen.git/out/horen-linux-x64/resources/app/dist/main.js:47577:22
    at Generator.next (<anonymous>)
    at /home/zxp-endeavouros/.cache/paru/clone/horen-git/src/horen.git/out/horen-linux-x64/resources/app/dist/main.js:48:71
    at new Promise (<anonymous>)
    at __awaiter (/home/zxp-endeavouros/.cache/paru/clone/horen-git/src/horen.git/out/horen-linux-x64/resources/app/dist/main.js:44:12)
    at /home/zxp-endeavouros/.cache/paru/clone/horen-git/src/horen.git/out/horen-linux-x64/resources/app/dist/main.js:47576:37
(Use `horen --trace-warnings ...` to show where the warning was created)
(node:204704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by kevinjobs** [comment]
newest commit has fixed it.

**Comment by zxp19821005** [comment]
`4ef8308` 运行报错。

**Comment by kevinjobs** [comment]
> 版本`4ef8308`编译运行后仍然报错。

还是原来的错误吗？

**Comment by zxp19821005** [comment]
是的

**Comment by kevinjobs** [comment]
> 是的

可能是没有 `process.env.APPDATA`，在这个文件夹下手动修改一下 APP_DATA_PATH 到你指定文件夹，或者 `/home/[usename]/.horen`
![screenshot-1707704888572](https://github.com/horenjs/horen/assets/22622334/e2a9fbae-250e-49c9-a01a-0cbefcd8908f)

**Comment by zxp19821005** [comment]
我刚才测试了一下，最新版的`gda52aa2`故障依旧。
修改源文件`app/main/src/constant.ts`在编译时就会报错，但是修改编译好的文件可以正常运行。
`const APP_DATA_PATH = "${XDG_DATA_HOME}";`

**Comment by zxp19821005** [comment]
这个问题我自己已经解决了。
无论是修改源文件，还是修改编译后的文件，都会报错，
我按照我所移植的Electron的软件，在脚本里面定义了`APPDATA`目录，目前正常使用。
```
#!/bin/sh
set -e
_APPDIR="/usr/lib/horen"
_RUNNAME="${_APPDIR}/app"
export PATH="${_APPDIR}:${PATH}"
export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
export APPDATA="${HOME}"
export ELECTRON_IS_DEV=0
export NODE_ENV=production
cd "${_APPDIR}"
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    exec electron28 "${_RUNNAME}" "$@" || exit $?
else
    exec electron28 "${_RUNNAME}" --no-sandbox "$@" || exit $?
fi
```

**Comment by zxp19821005** [comment]
目前已经提交到了ArchLinux的AUR：https://aur.archlinux.org/packages/horen-git
感谢！

**Comment by kevinjobs** [comment]
> 这个问题我自己已经解决了。 无论是修改源文件，还是修改编译后的文件，都会报错， 我按照我所移植的Electron的软件，在脚本里面定义了`APPDATA`目录，目前正常使用。
> 
> ```
> #!/bin/sh
> set -e
> _APPDIR="/usr/lib/horen"
> _RUNNAME="${_APPDIR}/app"
> export PATH="${_APPDIR}:${PATH}"
> export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
> export APPDATA="${HOME}"
> export ELECTRON_IS_DEV=0
> export NODE_ENV=production
> cd "${_APPDIR}"
> if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
>     exec electron28 "${_RUNNAME}" "$@" || exit $?
> else
>     exec electron28 "${_RUNNAME}" --no-sandbox "$@" || exit $?
> fi
> ```

这样修改也是可以的。猜测是在 Linux 上 Electron 启动时没有设置 process.env.APPDATA 的值。

尝试如下的修改应该是可以的。

```typescript
export const APP_DATA_PATH = `/home/[username]`;
```

**Comment by zxp19821005** [comment]
`sed "s|process.env.APPDATA|'/home/${USER}'|g" -i app/main/src/constant.ts`
使用这个是可以的，
`export const APP_DATA_PATH = `/home/[username]`;`会报错：
```
$ /usr/bin/horen %U
(node:552932) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/home/[username]'
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:552932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
